name: DAST Resubmit

on: workflow_dispatch
env: 
  Analyses_Name: Pre Scan Test

jobs:
  Veracode_DAST_Resubmit:
    runs-on: ubuntu-latest
    container:
      image: veracode/api-signing:latest

    steps:
      - name: Generate JSON and Resubmit JSON
        run: 
          sudo chmod 777 /tmp 
          echo "{\"name\":\"Pre Scan Test\",\"schedule\":{\"duration\":{\"length\":1,\"unit\":\"DAY\"},\"scheduled\":true,\"now\":true}}" > input.json
          export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
          export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
          ID=$(http --auth-type veracode_hmac GET "https://api.veracode.com/was/configservice/v1/analyses?name=${{ env.Analyses_Name }}" | jq -r '._embedded.analyses[0].analysis_id')
          echo ID:${ID}
          
          
      
        


              
              
