name: Detailed Report PDF

on: workflow_dispatch
env:
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}
  APP_NAME: VeraGHA

jobs:

  get_summary_report:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          repository: veracode/veracode-python-hmac-example
      - name: Display repo content
        run: |
          ls -la

      
        

  
      
          
          
