name: Veracode SCA Agent Demo
on: workflow_dispatch

jobs: 
  SCA: 
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        SCAN_DIR: "./app"
    steps:
        - name: Check out branch
          uses: actions/checkout@v2
          
        - name: Veracode Dependency Scanning
          # You may pin to the exact commit or the version.
          # uses: veracode/veracode-sca@9ab4d631fc9a0f14e1f9322c0d61bea90e924de1
          uses: veracode/veracode-sca@v2.0.65
          with:
            # Authorization token to query and create issues
            github_token: ${{ github.token }}
            # Run the SRCCLR with the `--quick` options
            quick: false
            # Show update advisor
            update_advisor: false
            # An attribute to instruct the action to create an issue from found vulnerability or just simple text output
            create-issues: false
            # A path within the repository where the build definition starts
            path: .
            # Run the SRCCLR in debug mode
            debug: false
            # Run the SRCCLR with the `--skip-collectors` options
            skip-collectors: false
            # Run the SRCCLR with the `--allow-dirty` option
            allow-dirty: false
            # Run the SRCCLR with the `--recursive` option
            recursive: false
            # Run the SRCCLR with the `--skip-vms` option
            skip-vms: false
