

name: Mitigation Pipeline Scanner 

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job to build and submit pipeline scan, you will need to customize the build process accordingly and make sure the artifact you build is used as the file input to the pipeline scan file parameter
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
  # build the application
    - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
      with: 
        java-version: '8'

    - name: Build with Maven
      run: mvn -B package --file app/pom.xml

      
    - name: Archive package
      uses: actions/upload-artifact@v2
      with:
        name: CodePackage
        path: '**/*.war'
        
    - name: Git Clone Action
  # You may pin to the exact commit or the version.
  # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
      uses: sudosubin/git-clone-action@v1.0.1
      with:
    # Repository owner and name. Ex: sudosubin/git-clone-action
        repository: https://github.com/tjarrettveracode/veracode-pipeline-mitigation.git
    # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
        platform: github
    # Relative path from current directory, where to clone.
    
    - name: find script
      run: |
        ls -la
      
  
  pipeline-scan:
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: veracode/pipeline-scan:latest
      options: --user root # our normal luser doesn't have privs to write to github directories

    steps:
    - name: Retrieve artifact
      uses: actions/download-artifact@v2
      with:
        name: CodePackage
        path: /github/home

    
    #  Submit  project to pipeline scan
    - name: Pipeline Scan
      run: |
        ls -la
