name: Pipeline Scan & SCA Verademo 

on:
  workflow_dispatch:

env:
  SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions for artifact upload
    permissions:
      contents: read
      packages: write
  
    steps:
    
    #Checks out repo
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Build with Maven
      run: |
        cd app/
        mvn -B clean package --file pom.xml
        ls target/
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: verademo-artifact
        path: app/target/verademo.war
        if-no-files-found: error
    
  pipeline-scan:
    needs: build
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    
    steps:
    
     - name: Set up JDK
       uses: actions/setup-java@v3
       with:
        java-version: '17'
        distribution: 'adopt'
        
     - name: Veracode Pipeline Scan
       uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.4
       with: 
         vid: ${{ secrets.VERACODE_API_ID }}
         vkey: ${{ secrets.VERACODE_API_KEY }}
         file: app/target/verademo.war
         token: ${{ secrets.GH_TOKEN }}
         summary_output: true
         sumary_output_file: results.txt
         project_name: Verademo Java
         project_url: https://github.com/justinbukstel/verademo
         project_ref: main
         debug: 1
         store_baseline_file: true
         store_baseline_file_branch: baseline
         create_baseline_from: standard
         fail_build: false
         
