name: Veracode SCA Agent Demo
on:
  workflow_dispatch:
  #pull_request:
   # branches: [ feature, main ]

jobs: 
  SCA: 
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        SCAN_DIR: "./app"
    steps:
        - name: Check out branch
          uses: actions/checkout@v2
          
        - name: Veracode Dependency Scanning
          run: |
              veracode_results=curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --update-advisor
              echo "$veracode_results" > veracode_results.txt
              echo "Results saved to veracode_results.txt."
              
              
          
          
