name: Summary Report

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
    workflow_dispatch: 

env:
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}

jobs: 
  veracode-api-call:
    runs-on: ubuntu-latest
  
    steps:
    - name: API Call
      uses: docker://veracode/api-signing:latest
      env: 
        API_ID: ${{ secrets.VERACODE_API_ID }}
        API_KEY: ${{ secrets.VERACODE_API_KEY }}
      args: |
        http --auth-type veracode_hmac https://api.veracode.com/api/authn/v2/api_credentials
      
          
          
