name: Summary Report

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
    workflow_dispatch: 


jobs:
  summary:
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download API Signing 
        uses: docker://veracode/api-signing:latest
        
      - name: Get App GUIDs
        run: http --auth-type=veracode_hmac GET https://api.veracode.com/appsec/v1/applications/?name=Verademo One
          
          
