name: Summary Report

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
    workflow_dispatch: 

env:
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}

jobs: 
  veracode-api-call:
    runs-on: ubuntu-latest
  
    steps:
    - name: API Call
      uses: docker://veracode/api-signing:latest
      with:
        args: |
          sh -c "veracode-api-signing --action GET --api_id $API_ID --api_key $API_KEY --url 'https://api.veracode.com/summaryreport/v1/applications?app_name=Verademo One'"
      
          
          
