name: Summary Report

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
    workflow_dispatch: 

env:
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}
  APP_NAME: VeraGHA


jobs: 
  veracode-api-call:
    runs-on: ubuntu-latest
  
    steps:
    - name: Get Application GUID for Verademo One
      id: get_guid
      env: 
        API_ID: ${{ secrets.VERACODE_API_ID }}
        API_KEY: ${{ secrets.VERACODE_API_KEY }}
      run: |
       while [[ -z "$GUID" ]]; do
       GUID=$(docker run --rm \
          -e VERACODE_API_KEY_ID=${{ env.API_ID }} \
          -e VERACODE_API_KEY_SECRET=${{ env.API_KEY }} \
          veracode/api-signing \
          http --auth-type veracode_hmac GET \
          https://api.veracode.com/appsec/v1/applications/?name=${{ env.APP_NAME }} \
          | jq -r '._embedded.applications[0].guid')
        if [[ -n "$GUID" ]]; then
          break
        fi
        echo "Waiting for first API call "
        sleep 15
       done

        
    - name: Summary 
      env: 
        API_ID: ${{ secrets.VERACODE_API_ID }}
        API_KEY: ${{ secrets.VERACODE_API_KEY }}
      run: |
         docker run --rm \
         -e VERACODE_API_KEY_ID=${{ env.API_ID }} \
         -e VERACODE_API_KEY_SECRET=${{ env.API_KEY }} \
          veracode/api-signing \
          http --auth-type veracode_hmac GET \
          https://api.veracode.com/appsec/v2/applications/$GUID/summary_report \



  
      
          
          
