name: Example Workflow
on: workflow_dispatch
env:
  MY_VAR: ''
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
    - name: Set the environment variable
      run: echo "MY_VAR=value" >> $GITHUB_ENV
  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Use the environment variable
      env: 
        My_VAR: ${{ job.job1.outputs.MY_VAR }}
      run: echo "The value of MY_VAR is:${{ env.MY_VAR }}"
