name: Summary Report GHA

on: workflow_dispatch
env:
  APP_NAME: VeraGHA
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}

jobs:

  get_summary_report:
    runs-on: ubuntu-latest
    container:
      image: veracode/api-signing:latest
    steps: 
      - name: get summary report
        run: |
          -e VERACODE_API_ID=${{ env.API_ID }}
          -e VERACODE_API_KEY_SECRET=${{ env.API_KEY }}
          GUID=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications/?name=${{ env.APP_NAME }}" | jq -r '._embedded.applications[0].guid')
          echo GUID: ${GUID}
    
  
