name: Summary Report GHA

on: workflow_dispatch
env:
  APP_NAME: VeraGHA

jobs:

  get_summary_report:
    runs-on: ubuntu-latest
    container:
      image: veracode/api-signing:latest
    steps: 
      - name: get summary report
        run: |
          export VERACODE_API_ID=${{ secrets.VERACODE_API_ID }}
          export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
          http --auth-type veracode_hmac https://api.veracode.com/api/authn/v2/api_credentials
    
  
